export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    LOGOUT: "/logout",
    REGISTER: "/register",
    VERIFY_EMAIL: "/verify-email",
    PROCESS_VERIFY_EMAIL: "/process-verify-email",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  USER: {
    PROFILE: "/user/profile",
    PASSWORD: "/user/password",
    PURCHASE: "/user/purchase",
    ADDRESS: "/user/address",
  },
  ADMIN: {
    USER: "/dashboard/user",
    STATISTIC: "/dashboard/statistic",
    AI_PREDICT: "/dashboard/ai-predict",
    ORDER: "/dashboard/order",
    PRODUCT: "/dashboard/product",
    PRODUCT_CREATE: "/dashboard/product/create",
    CATEGORY: "/dashboard/category",
    CATEGORY_CREATE: "/dashboard/category/create",
  },
  HOME: "/",
  SHOP: "/shop",
  CONTACT: "/contact",
  GUIDE: "/guide",
  INTRODUCE: "/introduce",
  CART: "/cart",
  CHECKOUT: "/checkout",
  THANK_YOU: "/thank-you",
};
